# Generated by Django 5.0.1 on 2024-04-15 13:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_advance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('total_medicineCost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('total_OtherCharge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('incomeDate', models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 599947, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='OtherCharge',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='daySpent',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='doctorFee',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='roomCharge',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='doctor',
            name='admitDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 584326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='consultation',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicineCost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='newAdvance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='problem',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='procedure',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 584326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='consultation',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='newAdvance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='problem',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='procedure',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='updateDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 599947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 584326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Orthodontics', 'Orthodontics'), ('Prosthodontics', 'Prosthodontics'), ('General dentist', 'General dentist'), ('Oral and maxillofacial surgery', 'Oral and maxillofacial surgery'), ('Endodontics', 'Endodontics'), ('Dentist', 'Dentist')], default='General dentist', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 584326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admitDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 599947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicineCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 599947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_expense', models.CharField(choices=[('Clinic Expense', 'Clinic Expense'), ('Non-Clinic Expense', 'Non-Clinic Expense')], default='Clinic Expense', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('description', models.TextField(max_length=500)),
                ('ExpenseDate', models.DateField(default=datetime.datetime(2024, 4, 15, 13, 40, 33, 599947, tzinfo=datetime.timezone.utc))),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
