# Generated by Django 5.0.1 on 2024-04-16 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminSigup',
        ),
    ]
