# Generated by Django 5.0.1 on 2024-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_rename_admin_adminsigup'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='newConsultation',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='newMedicineCost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type_expense',
            field=models.CharField(choices=[('Clinical Expense', 'Clinical Expense'), ('Non-Clinic Expense', 'Non-Clinic Expense')], default='Clinic Expense', max_length=50),
        ),
    ]
