# Generated by Django 5.0.1 on 2024-04-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_patient_newconsultation_patient_newmedicinecost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='newTotal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='newConsultation',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='newMedicineCost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20),
        ),
    ]
