# Generated by Django 5.0.1 on 2024-05-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_alter_patient_newtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateTimeField(),
        ),
    ]
