# Generated by Django 5.0.1 on 2024-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_alter_patientdischargedetails_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsigup',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/AProfilePic/'),
        ),
    ]
