# Generated by Django 5.0.1 on 2024-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_alter_adminsigup_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsigup',
            name='img',
        ),
        migrations.AddField(
            model_name='adminsigup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='admin_pic/'),
        ),
    ]
