# Generated by Django 5.0.1 on 2024-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_remove_adminsigup_img_adminsigup_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsigup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
