# Generated by Django 5.0.1 on 2024-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_adminsigup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsigup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='admin_pic/images'),
        ),
    ]
