# Generated by Django 5.0.1 on 2024-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
