# Generated by Django 5.0.1 on 2024-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_doctor_age_doctor_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
