# Generated by Django 5.0.1 on 2024-05-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_doctordischargedetails_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordischargedetails',
            name='problem',
        ),
    ]
